"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](lavender)\
$os\
$username\
[](fg:lavender bg:blue)\
$directory\
[](fg:blue bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:green)\
$nodejs\
[](fg:green bg:yellow)\
$python\
[](fg:yellow bg:peach)\
$cmd_duration\
[](fg:peach bg:pink)\
$time\
[](fg:pink)\
$line_break\
$character"""

add_newline = true
palette = "catppuccin_mocha"

[os]
disabled = false
style = "bg:lavender fg:crust"
[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:lavender fg:crust"
style_root = "bg:lavender fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:teal fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:teal fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol $version ]($style)'

[python]
symbol = ""
style = "bg:yellow fg:crust"
format = '[ $symbol $version(\($virtualenv\)) ]($style)'

[cmd_duration]
min_time = 500
style = "bg:peach fg:crust"
format = '[ 󱎫 $duration ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:pink fg:crust"
format = '[  $time ]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[palettes.catppuccin_mocha]
pink = "#f5c2e7"
mauve = "#cba6f7"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
base = "#1e1e2e"
crust = "#11111b"
