-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function()
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("systemctl --user start pipewire")
    hl.exec_cmd("systemctl --user start pipewire-pulse")
    hl.exec_cmd("systemctl --user start wireplumber")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("sleep 5 && blueman-applet")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("pavucontrol", { workspace = "special:volume silent" })
    hl.exec_cmd("waybar")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
